all:
	make -C runlength/
	make -C binarytree/
	make -C matrixmult/

measure:
	make -C runlength/ measure
	make -C binarytree/ measure
	make -C matrixmult/ measure

clean:
	make -C runlength/ clean
	make -C binarytree/ clean
	make -C matrixmult/ clean
