all:
	make -C tinycrypt/
	make -C rc5/
	make -C blowfish/

measure:
	make -C tinycrypt/ measure
	make -C rc5/ measure
	make -C blowfish/ measure

clean:
	make -C tinycrypt/ clean
	make -C rc5/ clean
	make -C blowfish/ clean
